{% set version = "17.0.0" %}
{% set name = "azure-mgmt-batch" %}
{% set sha256 = "8643385952eec318f8aa05ec63c61aef3bbbfefdfb80a74fd176dfd84aabb16a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - azure-common >=1.1,<2.dev0
    - azure-mgmt-core >=1.3.2,<2.0.0
    - msrest >=0.7.1
    - typing-extensions >=4.3.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - azure.mgmt
    - azure.mgmt.batch
  commands:
    - python -m unittest discover -p "test_*.py"

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/batch/azure-mgmt-batch
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Microsoft Azure Batch Management Client Library for Python

extra:
  recipe-maintainers:
    - johanneskoester
