schema_version: 1

context:
  version: 18.0.0
  name: azure-mgmt-batch
  sha256: 305eb51fb3f73b20927ef47b3b6f93e9e32dc939876c045f970bd386c07ba79c

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - azure-common >=1.1,<2.0.0
    - azure-mgmt-core >=1.3.2,<2.0.0
    - isodate >=0.6.1,<1.0.0


tests:
  - python:
      imports:
        - azure.mgmt
        - azure.mgmt.batch
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  summary: Microsoft Azure Batch Management Client Library for Python
  homepage: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/batch/azure-mgmt-batch

extra:
  recipe-maintainers:
    - johanneskoester
    - janjagusch
